# .streamlit/secrets.toml
DROPBOX_ACCESS_TOKEN = "your_dropbox_access_token_here"
FASTAPI_BACKEND_URL = "https://your-deployed-fastapi-app.onrender.com"
# Google Drive credentials.json content can be put here as a multi-line string
# or you can upload the file directly to Streamlit Cloud's secrets management.
# For simplicity in code, we'll assume credentials.json is uploaded to the repo
# or handled via Streamlit's specific secrets management for files.
